### ISSUE TITLE
Documentation: Submenu -> Reference -> Validators and File Validators cutted down

### ISSUE THREAD

**Issue by aight8** [zendframework/zend-validator#116]
Is cutted down when you have for example a 15" display - you can't scroll in the submenu. There is no other overview about all validators.

**Comment by adamlundrigan** [comment]
Confirmed.  The dropdown menu does not scroll, so only the first N entries under "Validators" can be seen.  The full listing of validators is also available if you click the "Validators" menu item instead of using that dropdown ([direct link](http://zendframework.github.io/zend-validator/set/)), so a low-priority bug.

**Comment by adamlundrigan** [comment]
I'm going to close this issue here as it's not related to the documentation for this component, and instead an issue with the ZF mkdocs theme.  I've opened an issue on that side (https://github.com/zendframework/zf-mkdoc-theme/issues/22)
