### ISSUE TITLE
Between validator options check

### ISSUE THREAD

**Issue by thomasvargiu** [zendframework/zend-validator#125]
In `Between` validator [constructor](https://github.com/zendframework/zend-validator/blob/release-2.8.1/src/Between.php#L84) it will throw an exception if `min` or `max` option is not defined, but only if number of options are 2. Why?

``` php
$validator = new \Zend\Validator\Between(['min' => 0, 'max' => 2]); // this works
$validator = new \Zend\Validator\Between(['min' => 0]); // this doesn't work

$validator = new \Zend\Validator\Between(['min' => 0, 'inclusive' => true]); // this works
$validator = new \Zend\Validator\Between(['min' => 0, 'foo' => 'bar']); // this works
$validator = new \Zend\Validator\Between(['bar' => 'foo', 'foo' => 'bar']); // this works
```

Another questions is: why should we check these options when there are default options?

**Comment by froschdesign** [comment]
> Why?

[The `if` construct is wrong.](https://github.com/zendframework/zend-validator/blob/release-2.8.1/src/Between.php#L81)

> why should we check these options when there are default options?

This is a good question!

**Comment by codisart** [comment]
I was checking this issue and I saw that the behaviour described by @thomasvargiu is now false since #174. For the cases : 
```php
$validator = new \Zend\Validator\Between(['min' => 0, 'inclusive' => true]);
$validator = new \Zend\Validator\Between(['min' => 0, 'foo' => 'bar']);
$validator = new \Zend\Validator\Between(['bar' => 'foo', 'foo' => 'bar']);
```
There is now a `Undefined index` error when we try to run these as shown in #183.

We can easily fix these but I agree with the two of you that the constructor's behavior is not that clear. And it seems to me that we need to define precisely how should work the constructor.
