### ISSUE TITLE
[ZF3] Rename all validators

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-validator#20]
Hi,

As part of the upcoming refactor, I'm suggesting to rename all validators to append "Validator" to their name. This make this more homogeneous with otehr part where we usually append a name. This also solve a common name clash where you are using both a Filter and Validator, but that have the same name (Int and Int,Float and Float), hence forcing to define a namespace alias.

What do you think? :)

ping @weierophinney @Maks3w

**Comment by Maks3w** [comment]
IMO add the namespace in the class name go against with the namespace principle also does not avoid name collision with validators provided by other libs. 

However you can quickly emulate a prefix importing the whole namespace 

    usr Zend\Validator;
    use Zend\Foo\Validator as FooValidator;

    new Validator\Between;
    new FooValidator\Between;

**Comment by manuakasam** [comment]
I'm with @Maks3w on this one. I don't think that there's a lot to gain, but
that would mean a LOT of code-base needed to be updated... (docs as well ;))
Personally I think I've encountered this just a few times, so I don't think
it's this big if an issue.

Maks3w <notifications@github.com> schrieb am So., 19. Juli 2015 um
08:53 Uhr:

**Comment by akrabat** [comment]
Not a fan.

**Comment by weierophinney** [comment]
@bakura10 "Int and Int,Float and Float" - these are ~~gone~~ deprecated now, due to PHP 7. :) As an example, `Zend\Filter\Int` became `Zend\Filter\ToInt`, while `Zend\I18n\Validator\Int` became `Zend\I18n\Validator\IsInt`; these new names also offer better semantics, as they indicate what they *do* (filter a value *to integer*, validate a value *is an integer*).

I often will alias validators and other plugins when I bring them into scope:


```php
use Zend\Validator\Timezone as TimezoneValidator;
```

so in that sense, having the suffix would be useful. However, like others, I'm not entirely sure there's much to gain. I could just have easily imported the validator namespace instead, in which case no suffixes are required:

```
use Zend\Validator;

$isInt = new Validator\IsInt();
```

Overall, I'm okay with leaving the names as-is. Leaving them will also simplify migrations.

**Comment by bakura10** [comment]
Actually are you sure that Int does not work in php7? A context sensitive lexer has been added to php7 recently.

Envoyé de mon iPhone

**Comment by gianarb** [comment]
This problem is easy to resolve with namespace alias.. IMO
