### ISSUE TITLE
NoRecordExists and RecordExists does not work when exclude paramter is of cass Where

### ISSUE THREAD

**Issue by Sebastian-Habiger** [zendframework/zend-validator#242]
As in line 300 of Zend\Validator\Db\AbstractDb the Where gets overridden the field to be checked gets lost. Changing this line to 

```
$select
                        ->where
                        ->addPredicate($this->exclude);
```

will fix the issue. But should that Where not be inverted?

**Comment by froschdesign** [comment]
I think it was only intended for two parameter types; string and array. Compare with the DocBlock:

https://github.com/zendframework/zend-validator/blob/87e743d11d49a157011a49a962c25e7a11adc7c5/src/Db/AbstractDb.php#L179-L190

The problem is that the `setExclude` method does not validate the value of the parameter.

**Comment by Sebastian-Habiger** [comment]
Thank you, you are right, my fault. I was sure I read somewhere in the documentation that a where is allowed.
Using a string instead of a Where is the solution.
