### ISSUE TITLE
container-interop/container-interop is abandoned, replace with psr/container

### ISSUE THREAD

**Issue by njandreasson** [zendframework/zend-validator#278]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-validator/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-validator/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

container-interop/container-interop is now abandoned in favour of psr/container.
As https://packagist.org/packages/container-interop/container-interop says:

> From v1.2, container-interop directly extends PSR-11 interfaces. Therefore, all containers implementing container-interop are now de-facto compatible with PSR-11.

Could we make this package require psr/container instead?

I'm using `zend/soap` which depends on `zend-uri -> zend-validator -> container-interop/container-interop` which has now started complaining about this dependency being abandoned.

Thanks in advance!

**Comment by weierophinney** [comment]
The only reason we depend on container-interop in this package is because the zend-servicemanager package still does. Unfortunately, it would be a BC break for us to change at this time (signature change), so it will have to wait to a new major version. This will not happen until after we transition the project to the Laminas Project.

It is, however, on our radar!
