### ISSUE TITLE
Require zend-math

### ISSUE THREAD

**Issue by larsnystrom** [zendframework/zend-validator#83]
This module requires zend-math to work (e.g. for `Validate\Csrf`) so there should be a dependency in `package.json`.

**Comment by Maks3w** [comment]
However when you are not using Csrf you don't need that dependecy.

We are aware of this kind of issues related with optional dependencies. We have choice to require as less dependencies as we can and delegate to the developer the task of require the optional dependencies he/she need.

**Comment by larsnystrom** [comment]
I think that is the wrong decision because it defeats the purpose of a dependency manager like composer. If you want people to manage dependencies manually you should probably not have a `package.json` at all.

**Comment by weierophinney** [comment]
Regardless of whether or not you feel the decision is "correct", it is the decision we've made. Since all validators are opt -in, installing the dependencies required for all validators is a disservice to those using a subset of them. If you're already using Doctrine, you'd likely be upset if this component also installed zend-db! 

The other option we have is to move any validators with additional dependencies into their own components, which is something we may do in the future. For now, we are declaring the bare minimum dependencies required to use the component, and marking anything else as a suggestion.

**Comment by larsnystrom** [comment]
I understand it's the decision you've made, but I still think it's the wrong one. It's not just that I wouldn't mind if you installed dependencies I didn't need, it's that I would actually prefer it to the alternative (which is manual dependency management).

However, I also think the better option is to move the validators into components of their own.

**Comment by webimpress** [comment]
Maybe in `suggest` section (in `composer.json`) should be said that `zend-math` component is required by the Csrf validator (as it for other suggestions)
