### ISSUE TITLE
Zend\Validator\File\ExcludeMimeType is missing the message templates

### ISSUE THREAD

**Issue by Jakovitz** [zendframework/zend-validator#90]
There are no error message templates in Zend\Validator\File\ExcludeMimeType.

**Comment by samsonasik** [comment]
it extends `Zend\Validator\File\MimeType`:

```php
class ExcludeMimeType extends MimeType
```
so, no need to re-define the $messageTemplates

**Comment by webimpress** [comment]
Unfortunately not, because in `Zend\Validator\File\MimeType` we have:

```
    protected $messageTemplates = [
        self::FALSE_TYPE   => "File has an incorrect mimetype of '%type%'",
        self::NOT_DETECTED => "The mimetype could not be detected from the file",
        self::NOT_READABLE => "File is not readable or does not exist",
    ];
```

so it is always using constants from `MimeType`.

We have the same constant names in `ExcludeMimeType`, but different constant values and we are using `self` in definition of the message template array. So @Jakovitz has right. It's a bug.

We can't use `static` instead of `self` in message template array definition (because of `"static::" is not allowed in compile-time constants`) so probably array have to be redefined in `ExcludeMimeType` ...

**Comment by samsonasik** [comment]
this can be closed then

**Comment by samsonasik** [comment]
can be closed in favor of https://github.com/zendframework/zend-validator/issues/92
